### ISSUE TITLE
from utils import download_chromedriver, has_chromedriver, Release

### ISSUE THREAD

**Issue by vassper** [dobizz/TikTok#7]
$ python run.py
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from utils import download_chromedriver, has_chromedriver, Release
ImportError: cannot import name 'Release' from 'utils' (C:\Users\d\TikTok\utils.py)

OS: Windows 10
Python 3.7
Run in console: GitBash

**Comment by iBlz** [comment]
i have the same error

**Comment by OVERPEY** [comment]
to fix this replace "Release" from file run.py to "get_latest_release"

**Comment by wheat009** [comment]
root@mmpp:~/TikTok# python3 run.py
Traceback (most recent call last):
  File "run.py", line 190, in <module>
    download_chromedriver(get_latest_release.AUTO_DETECT)
AttributeError: 'function' object has no attribute 'AUTO_DETECT'

The above problems occurred after modification
